# Generated by Django 4.0.2 on 2022-07-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
